name: Integration Test

on:
#  push:
#    branches:
#      - main
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: ${{ hashFiles('go.sum') }}
      - name: Setup Kind CLI
        run: |
          sudo curl -sSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-linux-amd64
          sudo chmod +x /usr/local/bin/kind
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        id: install
      - name: Setup Ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Setup Flux v2 CLI
        uses: fluxcd/flux2/action@main
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH} && chmod 700 ${SSH}
          ssh-keyscan github.com >> ${SSH}/known_hosts
      - name: Setup SSH key
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PCTL_BOT_PCTL_TEST_REPO_DEPLOY_KEY }}"
          ssh-add -l
      - name: Test
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          PATH=$PATH:$(go env GOPATH)/bin make integration-test
    env:
      GIT_TOKEN: ${{secrets.GIT_TOKEN}}
      SSH: "~/.ssh"
