name: Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "${HOME}/.ssh"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: ${{ hashFiles('go.sum') }}
      - name: Setup Kind CLI
        run: |
          sudo curl -sSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-linux-amd64
          sudo chmod +x /usr/local/bin/kind
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        id: install
      - name: Setup Ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Setup Flux v2 CLI
        uses: fluxcd/flux2/action@main
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Setup SSH key
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          EXAMPLES_KEY: ${{ secrets.PROFILES_EXAMPLES_PRIVATE_WEAVEWORKS_PCTL_BOT_DEPLOY_KEY }}
        run: |
          mkdir -p ${SSH_DIR}/git-keys
          echo "${{ secrets.PROFILES_EXAMPLES_PRIVATE_WEAVEWORKS_PCTL_BOT_DEPLOY_KEY }}" > ${SSH_DIR}/git-keys/weaveworks-profiles-examples-private
          chmod 600 ${SSH_DIR}/git-keys/weaveworks-profiles-examples-private
          echo "${{ secrets.PCTL_BOT_PCTL_TEST_REPO_DEPLOY_KEY }}" > ${SSH_DIR}/git-keys/weaveworks-pctl-test-repo
          chmod 600 ${SSH_DIR}/git-keys/weaveworks-pctl-test-repo
          cp ${{ github.workspace }}/scripts/ssh_command.sh ${SSH_DIR}/ssh_command
          ls -l $SSH_DIR}/
      - name: Test
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_SSH_COMMAND: ${SSH_DIR}/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "1"
        run: |
          ls -l ${SSH_DIR}/
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          PATH=$PATH:$(go env GOPATH)/bin make integration